try {
export const errors = [];

} catch (error) { console.error(error); }